pipeline{
    agent any
    
    stages{
        stage('Checkout'){
           steps{ 
               echo 'Checking out!!!'
           }
        }
        stage('Compile'){
           steps{ 
               echo 'Compile!!!'
           }
        }
        stage('Test'){
           steps{ 
               echo 'Testing!!!'
           }
        }
         stage('Deploy'){
           steps{ 
               echo 'Deploying!!!'
           }
        }
    }
}